export type Item={id:string;title:string;created:string;[key:string]:string|number|null};
export type Data={profile:Record<string,any>;[key:string]:any};
export const collections=['goals','projects','tasks','homework','lessons','events','goalMilestones','fllMissions','fllAttempts','fllSessions','workouts','exercises','portfolioProjects','achievements','skills','reviews','focusSessions','lessonPrep'] as const;
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Aqtau',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const localTime=()=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Aqtau',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
export const minutes=(s:string)=>{const [h,m]=s.split(':').map(Number);return h*60+m};
export const clock=(n:number)=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
export function planDay(data:Data,date:string){const weekday=new Date(date+'T12:00:00+05:00').getDay();const lessons=(data.lessons||[]).filter((x:Item)=>x.weekday===weekday).sort((a:Item,b:Item)=>String(a.start).localeCompare(String(b.start)));const fixed=(data.events||[]).filter((x:Item)=>x.date===date).map((x:Item)=>({...x,start:minutes(String(x.start)),end:minutes(String(x.end))}));let cursor=lessons.length?minutes(String(lessons.at(-1).end))+(data.profile.travel||40):16*60; const sleep=minutes(data.profile.sleep||'22:30');const planned:any[]=[];const overflow:Item[]=[];const pending=[...(data.homework||[]),...(data.tasks||[])].filter(x=>x.status!=='Done'&&(!x.due||x.due<=date)).sort((a,b)=>String(a.due||date).localeCompare(String(b.due||date)));for(const x of pending){const duration=Number(x.duration||30);let conflict; do{conflict=fixed.find((f:any)=>cursor<f.end&&cursor+duration>f.start);if(conflict)cursor=conflict.end+10;}while(conflict);if(cursor+duration>sleep-30){overflow.push(x);continue;}planned.push({...x,start:cursor,end:cursor+duration});cursor+=duration+10;}return {lessons,planned,fixed,overflow,sleep};}

export function nextDate(date:string){const d=new Date(date+'T12:00:00+05:00');d.setDate(d.getDate()+1);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Aqtau',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
