export type Field={key:string;label:string;type?:string;options?:string[];required?:boolean};
const title:Field={key:'title',label:'Title',required:true};const due:Field={key:'due',label:'Due date',type:'date',required:true};const status:Field={key:'status',label:'Status',options:['Not Started','In Progress','Done']};const deadline:Field={key:'deadline',label:'Deadline',type:'date'};
export const forms:Record<string,Field[]>={
tasks:[title,due,{key:'duration',label:'Estimated minutes',type:'number'},status,{key:'priority',label:'Priority',options:['Normal','Important','Urgent']},{key:'projectId',label:'Related project',type:'project'},{key:'top',label:'Today’s Top 3',type:'checkbox'}],
homework:[{key:'subject',label:'Subject',required:true},{...title,label:'Assignment'},{key:'assigned',label:'Assigned date',type:'date'},due,{key:'duration',label:'Estimated minutes',type:'number'},status,{key:'priority',label:'Priority',options:['Normal','Important','Urgent']}],
goals:[title,{key:'horizon',label:'Time horizon',options:['Today','This Week','This Month','3 Months','This Year','Long Term','Custom Date']},deadline,{key:'why',label:'Why this matters',type:'textarea'},{key:'nextAction',label:'Next action'}],
projects:[title,{key:'description',label:'Description',type:'textarea'},{key:'status',label:'Status',options:['Active','Paused','Completed']},deadline,{key:'nextAction',label:'Next action',required:true},{key:'goalId',label:'Related goal',type:'goal'}],
lessons:[{...title,label:'Subject'},{key:'weekday',label:'Weekday',type:'weekday'},{key:'start',label:'Start',type:'time',required:true},{key:'end',label:'End',type:'time',required:true},{key:'room',label:'Room'},{key:'teacher',label:'Teacher'}],
events:[title,{key:'date',label:'Date',type:'date',required:true},{key:'start',label:'Start',type:'time',required:true},{key:'end',label:'End',type:'time',required:true},{key:'category',label:'Category',options:['Personal','FLL','Training','Food','Break','Travel','Exam']}],
fllMissions:[title,{key:'points',label:'Points',type:'number'},{key:'status',label:'Status',options:['Not Started','Building','Programming','Testing','Stable']},{key:'strategy',label:'Strategy',type:'textarea'},{key:'attachment',label:'Attachment'},{key:'program',label:'Program'},{key:'position',label:'Starting position'},{key:'notes',label:'Notes',type:'textarea'},{key:'goalId',label:'Related goal',type:'goal'}],
fllSessions:[title,{key:'date',label:'Date',type:'date',required:true},{key:'missionId',label:'Mission',type:'mission'},{key:'duration',label:'Minutes',type:'number'},{key:'best',label:'Best result'},{key:'problems',label:'Problems',type:'textarea'},{key:'nextAction',label:'Next action'}],
workouts:[title,{key:'date',label:'Date',type:'date',required:true},{key:'activity',label:'Activity',options:['Home','Football','Swimming','Gym','Recovery']},{key:'status',label:'Status',options:['Planned','Completed']},{key:'rating',label:'How did it feel?',options:['Good','Easy','Hard']}],
portfolioProjects:[title,{key:'projectId',label:'Related project',type:'project'},{key:'year',label:'Year',type:'number'},{key:'role',label:'Role'},{key:'category',label:'Category',options:['Robotics','Programming','Startups','Research','Education','Competitions','Design','Other']},{key:'about',label:'About',type:'textarea'},{key:'problem',label:'Problem',type:'textarea'},{key:'solution',label:'Solution',type:'textarea'},{key:'technology',label:'Technology'},{key:'results',label:'Results',type:'textarea'},{key:'url',label:'Project link',type:'url'},{key:'public',label:'Public — explicitly include in portfolio',type:'checkbox'}],
achievements:[title,{key:'date',label:'Date',type:'date',required:true},{key:'category',label:'Type',options:['Competition','Certificate','Award','Course','Project milestone','School','Robotics']},{key:'organization',label:'Organization'},{key:'description',label:'Description',type:'textarea'},{key:'projectId',label:'Related project',type:'project'},{key:'url',label:'Certificate link',type:'url'},{key:'public',label:'Public — explicitly include in portfolio',type:'checkbox'}],
skills:[title,{key:'started',label:'Started',type:'date'},{key:'stage',label:'Stage',options:['Learning','Practicing','Confident']},{key:'evidence',label:'Evidence / related projects'}],
goalMilestones:[title,{key:'done',label:'Completed',type:'checkbox'}],
exercises:[title,{key:'sets',label:'Sets',type:'number'},{key:'reps',label:'Reps / time'}],
reviews:[title,{key:'period',label:'Period',type:'month'},{key:'progress',label:'Biggest progress',type:'textarea'},{key:'attention',label:'What needs attention',type:'textarea'},{key:'focus',label:'Next month’s focus',type:'textarea'}]
};
