'use client';
import {ReactNode,useEffect,useRef} from 'react';
import {X,Plus,ArrowUpRight} from 'lucide-react';
export function Logo({large=false}:{large?:boolean}){return <svg className={large?'logo large':'logo'} viewBox="0 0 64 64" fill="none" aria-label="BEKBOLAT OS"><path d="M16 48V16h17c13 0 15 16 3 17 15 0 13 15 0 15H16Z" stroke="currentColor" strokeWidth="5"/><path d="m29 40 22-22m-12 0h12v12" stroke="currentColor" strokeWidth="4"/><circle cx="32" cy="32" r="29" stroke="currentColor" strokeOpacity=".15"/></svg>}
export function ProgressBar({value}:{value:number}){return <div className="progress"><span style={{width:`${value}%`}}/></div>}
export function Panel({title,tag,children,action,className=''}:{title:string;tag?:string;children:ReactNode;action?:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-head"><div><span className="eyebrow">{tag}</span><h2>{title}</h2></div>{action}</div>{children}</section>}
export function Empty({text,action,onClick}:{text:string;action?:string;onClick?:()=>void}){return <div className="empty"><span className="empty-symbol">＋</span><p>{text}</p>{action&&<button className="text-btn" onClick={onClick}>{action} <Plus size={14}/></button>}</div>}
export function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const prior=document.activeElement as HTMLElement;const el=ref.current;el?.querySelector<HTMLElement>('input,button')?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'&&el){const nodes=Array.from(el.querySelectorAll<HTMLElement>('button,input,select,textarea,a'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);prior?.focus()}},[close]);return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal" role="dialog" aria-modal="true" aria-label={title} ref={ref}><div className="panel-head"><h2>{title}</h2><button className="icon-btn" aria-label="Close" onClick={close}><X size={20}/></button></div>{children}</div></div>}
export function GoalCard({item,milestones,onOpen}:{item:any;milestones:any[];onOpen:()=>void}){const done=milestones.filter(x=>x.done).length;const value=milestones.length?Math.round(done/milestones.length*100):0;return <button className="entity-card" onClick={onOpen}><div className="row"><span className="badge">{item.horizon}</span><ArrowUpRight size={18}/></div><h3>{item.title}</h3><p>{item.nextAction||'Add the next milestone'}</p><ProgressBar value={value}/><div className="row muted"><span>{done} / {milestones.length} milestones</span><span>{value}%</span></div>{item.deadline&&<small>Due {item.deadline}</small>}</button>}
export function ProjectCard({item,tasks,onOpen}:{item:any;tasks:any[];onOpen:()=>void}){const value=tasks.length?Math.round(tasks.filter(x=>x.status==='Done').length/tasks.length*100):0;return <button className="entity-card" onClick={onOpen}><div className="row"><span className="project-letter">{item.title.slice(0,1)}</span><span className="badge">{item.status}</span></div><h3>{item.title}</h3><p>{item.description||'Your next idea, in progress.'}</p><ProgressBar value={value}/><div className="row muted"><span>{tasks.length} tasks</span><span>{value}%</span></div><div className="next-action"><span className="eyebrow">NEXT ACTION</span><p>{item.nextAction}</p></div></button>}
